// Auto-generated by scripts/sync-release.mjs. Do not edit manually.
export const RELEASE_INFO = {
    "versionCode": 662,
    "versionName": "1.0.662",
    "releaseChannel": "stable",
    "releaseNotes": [
        "修复部分 AI 渠道“思考中”时间稍长就被误判为连接超时的问题：AI 出正文前的分析思考阶段不再计入超时等待，正文会正常继续输出，不会中途断开。",
        "修复从商店、任务或 NPC 手中获得的「货币类」物品（如通用流通货币、银票、灵晶等）只能占着背包、无法花出去的问题：这类物品现在可以在背包里一键兑换为对应金钱入账。",
        "修复在手机 App 里导出小说或分解分享包后提示“已保存”却在文件管理器里找不到的问题：导出时会弹出系统分享面板，可直接保存到手机文件、发送到微信或网盘。",
        "修复大型存档读取较慢时界面长时间没有反馈、容易误以为卡死的问题：读取超过一定时间会显示“正在恢复存档状态，请耐心等待”的提示。",
        "官网：https://msjh.bacon159.pp.ua/",
        "备用站：https://msjh.bacon.de5.net/"
    ],
    "releaseHistory": [
        {
            "versionName": "1.0.662",
            "versionCode": 662,
            "releasePublishedAt": "2026-09-05T11:36:10+08:00",
            "releaseNotes": [
                "修复部分 AI 渠道“思考中”时间稍长就被误判为连接超时的问题：AI 出正文前的分析思考阶段不再计入超时等待，正文会正常继续输出，不会中途断开。",
                "修复从商店、任务或 NPC 手中获得的「货币类」物品（如通用流通货币、银票、灵晶等）只能占着背包、无法花出去的问题：这类物品现在可以在背包里一键兑换为对应金钱入账。",
                "修复在手机 App 里导出小说或分解分享包后提示“已保存”却在文件管理器里找不到的问题：导出时会弹出系统分享面板，可直接保存到手机文件、发送到微信或网盘。",
                "修复大型存档读取较慢时界面长时间没有反馈、容易误以为卡死的问题：读取超过一定时间会显示“正在恢复存档状态，请耐心等待”的提示。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.661",
            "versionCode": 661,
            "releasePublishedAt": "2026-08-30T00:45:55+08:00",
            "releaseNotes": [
                "修复开局偶发\"世界观生成解析失败: 输出为空\"：部分 Gemini 桥接渠道会偶发返回 200 空内容，现在会自动重试（最多 3 次），仍失败时给出明确原因提示（安全拦截/思考模型无正文/服务瞬时异常），方便判断与换渠道。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.660",
            "versionCode": 660,
            "releasePublishedAt": "2026-08-29T23:34:40+08:00",
            "releaseNotes": [
                "修复开局失败：使用 Gemini 系模型（含各类 Gemini 直通渠道）开局时，不再报 \"Requests ending with a model turn are not supported\" 400 错误。开局请求现在会自动把格式预填充转换为 Gemini 兼容的续写指令，世界观与开局剧情可正常生成。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.659",
            "versionCode": 659,
            "releasePublishedAt": "2026-08-29T20:49:05+08:00",
            "releaseNotes": [
                "修复白色模式下部分状态标签看不清的问题：酒馆预设开启状态、图片迁移通知等彩色提示在浅色主题下改为浅底深字，清晰可读，不再出现深色底配深色字的情况。",
                "生成流程图中的渠道和模型名称现在完整显示：长名称会自动换行，不再被省略号截断，检查各阶段配置更省心。",
                "修复云端游玩存档清单读取失败（提示 HTTP 404）的问题：8 月 9 日前开通云端游玩的老账号，云端存档列表与下载已全部恢复。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.658",
            "versionCode": 658,
            "releasePublishedAt": "2026-08-29T00:01:09+08:00",
            "releaseNotes": [
                "修复自动入队过于宽松的问题：主线人物、路人镖师等只是带路、护送一程、短暂同行或跟着人群，不会再被自动拉进队伍；明确答应入队、结伴同行、追随主角的角色仍会正常入队。队伍列表从此只保留真正的长期同伴，不想让某人跟队也可以随时在队伍页移除。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.657",
            "versionCode": 657,
            "releasePublishedAt": "2026-08-28T22:29:44+08:00",
            "releaseNotes": [
                "修复钱财更新不同步：AI 更新银子、金元宝、铜钱等货币后，左侧「钱财」面板与变量面板会立即显示正确金额，不再出现金额卡在旧值、被悄悄改回或与实际余额对不上的情况。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.656",
            "versionCode": 656,
            "releasePublishedAt": "2026-08-28T19:22:09+08:00",
            "releaseNotes": [
                "修复物品生图：生成物品图片时不再把装备简介里的效果说明、数值和角色名当成画面内容，改为只按物品的外观、材质与形制出图，蓑衣、披风这类自制物件也能画出更贴合描述的样子。",
                "修复钱财显示：仙侠（灵石/灵玉）、现代（现金/存款）、末世、奇幻等题材下，左侧「钱财」一栏不会再错误显示为 0，角色实际持有的货币会正确显示。",
                "修复小说模式分解补漏：长篇拆解时内嵌的可见性信息（谁知道／谁不知道／是否仅读者视角可见）能正确恢复，跨午夜的时间会自动顺延到次日，不再卡在同一处反复重试。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.655",
            "versionCode": 655,
            "releasePublishedAt": "2026-08-27T22:17:50+08:00",
            "releaseNotes": [
                "修复生成商人类 NPC 时，其人物档案被错误写进女主角档案的问题：现在通过正文自动生成的新商人 NPC 会作为独立人物正确建档，不会污染女主角的资料。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.654",
            "versionCode": 654,
            "releasePublishedAt": "2026-08-25T22:21:28+08:00",
            "releaseNotes": [
                "修复拍卖行寄售收入丢失：在「天下拍卖行」寄售的物品成交后，下一回合系统结算的金钱偶尔会被剧情变量更新覆盖而凭空消失；现在寄售收入会在变量结算后正确入账，玩家的钱不再无故减少。",
                "增强金钱结算稳定性：脚本发放的金钱与 AI 剧情变量更新现在采用统一的补偿机制，无论二者到达顺序如何，寄售收入与任务奖励都能正确累加。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.653",
            "versionCode": 653,
            "releasePublishedAt": "2026-08-20T00:40:23+08:00",
            "releaseNotes": [
                "修复队友/NPC 在剧情或战斗回合后，境界层级偶尔被错误重置为第一层的问题：现在会保留已有境界，只有剧情明确发生破境、散功或永久跌境时才更新。",
                "修复整组社交档案更新时省略境界字段会间接清空境界的问题，好感度等正常更新不受影响。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.649",
            "versionCode": 649,
            "releasePublishedAt": "2026-08-16T07:58:04.831Z",
            "releaseNotes": [
                "创意工坊全面修复：社区模式包列表已恢复显示，包括最新投稿在内的全部模式包、酒馆预设与生图工作流均可正常浏览和下载，无需重新投稿。",
                "创意工坊数据加固：投稿数据的保存方式升级为原子写入，即使云端出现瞬时故障，也不会再出现模式包列表被清空的问题。",
                "联机账号修复：老玩家在切换新服务器后无法登录联机账号的问题已解决，迁移前后的账号现在都能正常登录。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.648",
            "versionCode": 648,
            "releasePublishedAt": "2026-08-15T19:41:07.069+08:00",
            "releaseNotes": [
                "大型存档与旧存档谱系处理更省内存：减少一次性读取完整存档造成的卡顿、内存不足和闪退风险。",
                "物品图库改为分页加载：打开图库不再扫描整份存档，支持继续加载、读取失败提示与一键重试；本地图片缺失或损坏时可回退到远程图片。",
                "修复模型列表与连接测试的并发覆盖问题：切换接口、地址、密钥或模型后，旧请求结果不会再覆盖当前选择，校验提示也会正确保留。",
                "恢复“双人成行 v11.0 墨染江湖适配版”酒馆预设，并完整保留提示词顺序、启用状态、正则脚本和生成参数。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.647",
            "versionCode": 647,
            "releasePublishedAt": "2026-08-15T14:15:25.339+08:00",
            "releaseNotes": [
                "修复 GitHub 云端同步授权失败（提示 redirect_uri 不匹配）的问题：已同步迁移后的 Cloudflare 账号密钥，OAuth 回调地址现在能与 GitHub App 登记地址正确匹配。",
                "修复 APK 内前端环境变量在打包后丢失的问题：Vite 构建期变量现在能正确内联到生产包，GitHub 同步功能在 APK 端不再因缺少 Client ID 而无法工作。",
                "增强 OAuth 错误提示：遇到回调地址不一致时会显示具体的 redirect_uri 和 client 类型，方便排查。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.646",
            "versionCode": 646,
            "releasePublishedAt": "2026-08-07T22:34:42.661+08:00",
            "releaseNotes": [
                "修复自定义模型（类脑、one-api 等 glm 中转站）发消息 404：填写的接口地址会被原样尊重，不再被错误改写成智谱私有地址导致发不出消息。",
                "修复开局“非流式输出”设置不生效：在设置里开启“启用非流式输出”后，开局剧情也会走非流式，长文本输出更稳定、不再中途断开。",
                "修复行动选项误报缺失：AI 偶尔省略格式标签时，系统会自动补齐结构，不再把原本正常的剧情误判为缺少行动选项而强制重生成。",
                "接口兼容性增强：智谱、类脑等接口的地址识别更精准，路径中带 bigmodel.cn 的中转站不再被误当成智谱官方；行动选项的英文别名（options / choice 等）也能正确识别。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.645",
            "versionCode": 645,
            "releasePublishedAt": "2026-08-07T19:54:50.786+08:00",
            "releaseNotes": [
                "云存档下载修复：修复自定义同步地址为空时 GitHub 云存档下载提示 “no protocol” 的问题，现在主站与备用站双代理都可用。",
                "自定义模型列表可正常加载：OpenCode 等自定义 OpenAI 兼容接口现在能正确拉取可用模型列表（解决 WebView 内 CORS 导致的获取失败）。",
                "创意工坊编辑不再累积重复内容：单模块编辑后不会再出现 “A 不属于 B / A 属于 B” 这样的重复段落。",
                "剧情正文正确分段：AI 返回的长正文现在会按【角色】/【旁白】等标签正确换行分段，阅读更清晰。",
                "酒馆预设保留主剧情约束：启用酒馆预设时不再丢失“去魅主”叙事总约束，NPC 也不再异常扎堆在主角身边。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.634",
            "versionCode": 634,
            "releasePublishedAt": "2026-08-01T19:25:58+08:00",
            "releaseNotes": [
                "修复 AI 流式输出被上游提前截断时剧情中断的问题：系统会自动改用非流式重试，完整响应即使省略结束信号也不会被误判。",
                "修复启用酒馆预设后“严格旁白/对白格式”可能失效的问题：开关开启时会继续要求旁白与角色对白使用正确标签。",
                "修复网站更新后旧设置模块加载失败可能让整个游戏进入错误页的问题：异常现在只影响设置弹窗，可关闭或刷新恢复。",
                "修复重ROLL遇到后台处理或自动存档尚未完成时可能残留或误删存档的问题：现在只清理当前回合对应的自动存档，并保留上一轮有效存档。",
                "修复短对白后的叙事被并入人物气泡的问题：同角色多段短对白会独立显示，中间叙事恢复为旁白，并支持对白前的动作描述。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.633",
            "versionCode": 633,
            "releasePublishedAt": "2026-07-30T21:43:32+08:00",
            "releaseNotes": [
                "修复双判定框或长判定结果时正文被吞没的问题：判定结果与剧情正文现在会分别完整显示，不再只剩“成功/失败”。",
                "修复角色属性被格式（如斜体强调）包裹时容貌、音响、身高等属性不变化、不掷骰的问题：属性增减与判定现在正常生效。",
                "NPC 私密生图相关调试从隐藏后门改为正式“NPC 调试日志”开关（默认关闭），不再误弹无关报错。",
                "已知项：客户端“cf”禁忌词目前尚未生效，已记录并会在后续版本补充；建议正文暂避免直接使用该词。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.632",
            "versionCode": 632,
            "releasePublishedAt": "2026-07-29T19:22:50+08:00",
            "releaseNotes": [
                "全桌面分辨率（含 1920×1080）选项区域不再侵占正文：长选项列表自动约束高度并支持滚动。",
                "行动按钮文本默认换行，超长选项不再把正文挤出屏幕；短屏紧凑规则继续生效。",
                "修复移动端网页行动选项无法左右滑动的问题：恢复横向滑动手势，选项较多时仍可滑动查看。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.631",
            "versionCode": 631,
            "releasePublishedAt": "2026-07-29T00:19:50+08:00",
            "releaseNotes": [
                "全桌面分辨率（含 1920×1080）选项区域不再侵占正文：长选项列表自动约束高度并支持滚动。",
                "行动按钮文本默认换行，超长选项不再把正文挤出屏幕；短屏紧凑规则继续生效。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.630",
            "versionCode": 630,
            "releasePublishedAt": "2026-07-28T20:40:37+08:00",
            "releaseNotes": [
                "修复正文校验偶尔把“而是”“于是他”“而是他们”等普通叙事短语误判为人物的问题。",
                "正文内容正常时，现在可以直接使用自动修复应用或手动编辑后应用，无需重新生成整段剧情。",
                "同时保护“于是之”等真实姓名，并继续拦截真正缺少【角色名】标签的对白。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.629",
            "versionCode": 629,
            "releasePublishedAt": "2026-07-27T00:07:28+08:00",
            "releaseNotes": [
                "修复 VPS 备用站点击 APK 下载后提示 Failed to fetch 的问题，现在可直接正常下载。",
                "根据国内无代理环境完整 APK 实测，将 VPS 设为首选下载渠道；夸克、OneDrive 和 GitHub 等渠道继续提供自动回退。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.628",
            "versionCode": 628,
            "releasePublishedAt": "2026-07-24T03:24:27+08:00",
            "releaseNotes": [
                "修复修仙、超凡、无限流等高龄高境界角色被误画成老太婆或老头的问题：现在会结合题材、境界与外观设定判断视觉年龄，不再只按真实年龄粗暴老化。",
                "剧情称呼、角色档案、主角生图、NPC 生图统一改用同一套视觉年龄逻辑；高龄角色可以保留资历感，但不会默认被写成老妇、老妪等老态称呼。",
                "现实向角色仍按现实年龄表现：现实 80 岁角色会继续保持符合年龄的老年外观，不会被误年轻化。",
                "加强成人内容安全校验：真实未成年或明确幼态外观角色，会被禁止成人私密生图，减少不合规生成。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.627",
            "versionCode": 627,
            "releasePublishedAt": "2026-07-22T23:27:49+08:00",
            "releaseNotes": [
                "新增多能力体系境界 DIY：武者、道士、法师等体系可以分别设置境界、能量类型、主副体系定位，并通过共通战力档位建立跨体系强度对应关系。",
                "角色可选择主体系并兼修副体系；系统会保护至少一个可用主体系，避免开局配置成无法选择主修路线。",
                "世界演化现在会结算离场 NPC 的成长：符合条件时可提升对应体系境界，并获得、穿戴或替换装备，重新登场时会保留演化结果。",
                "离场 NPC 结算加入身份、体系、突破机缘与装备一致性校验，减少重名角色、错体系晋升或装备状态不同步。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.595",
            "versionCode": 595,
            "releasePublishedAt": "2026-07-12T15:48:01+08:00",
            "releaseNotes": [
                "酒馆预设模式现在会完整接管所选预设的文风、格式与思维链，不再混入内置叙事指令，风格更贴合预设本身。",
                "创意工坊酒馆预设：同名多版本只显示最新版本，默认选中与加载体验更顺畅。",
                "修复物品配图偶尔生成空白“塑料板”的问题：中文描述的物品（含任务道具）现在能正确出图。",
                "江湖势力关系图：连线现在准确连到势力图标上，图例可点击筛选（友好/中立/敌对），并移除连线上多余文字。",
                "优化编辑存档并重新解析后的卡顿，编辑的那一回合现在能更快显示。",
                "开局主线任务改由 AI 按剧情生成，不再是固定模板任务。",
                "修复对话人物与道友录记录对不上（显示成“角色9”等占位名）的问题。",
                "修复部分 NPC 境界显示成不存在的“初境”的问题，现在按题材正确显示。",
                "修复剧情正文偶尔混入变量、规划、选项等内部内容的问题，阅读更干净。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.594",
            "versionCode": 594,
            "releasePublishedAt": "2026-07-12T13:44:00+08:00",
            "releaseNotes": [
                "修复部分设备打开应用时白屏/启动失败的问题（初始化脚本报错），现在可正常进入游戏。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.593",
            "versionCode": 593,
            "releasePublishedAt": "2026-07-12T13:27:43+08:00",
            "releaseNotes": [
                "新增物品图库：可把满意的物品图片收藏起来，之后同类物品直接复用，减少重复生成。",
                "物品生图支持中文提示词（Grok / GPT 等云端模型），描述更准、成图更贴合物品本身。",
                "图片生成新增代理开关与连接测试，本地、在线与 APK 环境下的生图连通性更稳定。",
                "人物（主角 / NPC / 伙伴）支持直接使用外部图片链接作为立绘。",
                "新增天赋「叙事约束」，可让 AI 在剧情生成中稳定遵守特定设定。",
                "创意工坊解锁性别比例、平静值等参数，开局配置更自由。",
                "新增多货币体系与汇率玩法（特定题材模式），经济体验更丰富。",
                "修复移动端输入框被浏览器界面遮挡的问题。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.592",
            "versionCode": 592,
            "releasePublishedAt": "2026-07-11T22:04:21+08:00",
            "releaseNotes": [
                "修复剧情正文末尾偶尔混入内部状态文本（时间、好感度、记忆等）的问题：这些内部更新会照常生效，但不再显示在故事正文里打断阅读。",
                "修复江湖势力页面把势力显示成内部编号（如 FCT-001）且关系图缺失的问题：现在恢复正确的势力名称显示与完整的势力关系图。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.591",
            "versionCode": 591,
            "releasePublishedAt": "2026-07-11T19:48:26+08:00",
            "releaseNotes": [
                "修复 ComfyUI 临时工作区重启后可能显示上一次同名旧图的问题，角色头像与场景图不再无故串图。",
                "ComfyUI 生图默认启用随机种子，同一提示词也能产生更丰富的结果；可在图片功能设置中关闭，导入 PNG 指定的种子仍优先生效。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.589",
            "versionCode": 589,
            "releasePublishedAt": "2026-07-10T12:44:37+08:00",
            "releaseNotes": [
                "修复创意工坊本地导入酒馆预设后看不到发布入口的问题：本地测试通过的酒馆预设现在可以直接发布到社区。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.588",
            "versionCode": 588,
            "releasePublishedAt": "2026-07-09T12:49:48.319+08:00",
            "releaseNotes": [
                "修复创意工坊酒馆预设无法点击开关编辑的问题：玩家现在可以直接调整“双人成行”等工坊预设，系统会自动保存为自己的本地副本。",
                "保留创意工坊默认配置：玩家修改自己的本地副本时，不会影响工坊预设原始默认开关状态。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.587",
            "versionCode": 587,
            "releasePublishedAt": "2026-07-09T01:00:18.713+08:00",
            "releaseNotes": [
                "修复酒馆预设下拉框：现在会显示完整创意工坊酒馆预设，包括社区贡献的“双人成行v10.0_青云上_MoRan墨染江湖净化完整版”。",
                "保护创意工坊预设：内置/社区工坊预设不会被误删。",
                "优化本地上传预设删除：删除玩家本地上传的酒馆预设前会弹出确认，减少误操作。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.586",
            "versionCode": 586,
            "releasePublishedAt": "2026-07-09T00:23:53+08:00",
            "releaseNotes": [
                "修复酒馆预设下拉框：创意工坊酒馆预设会始终显示在当前预设列表中，方便直接切换使用。",
                "保护创意工坊预设：内置/社区工坊预设不会被误删。",
                "优化本地上传预设删除：删除玩家本地上传的酒馆预设前会弹出确认，减少误操作。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.585",
            "versionCode": 585,
            "releasePublishedAt": "2026-07-08T23:32:18+08:00",
            "releaseNotes": [
                "修复部分 OpenAI 兼容接口连接失败的问题：百度千帆 DeepSeek、类脑、智谱等地址已包含 /v2 或 /api/paas/v4 这类版本路径时，游戏会尊重玩家填写的地址，不再额外插入错误的 /v1。",
                "修复创意工坊小说分解模块大包上传与下载：较大的分享 ZIP 会自动分片上传，下载导入时会自动合并校验，减少大包卡住或提示暂不可下载。",
                "优化创意工坊酒馆预设展示：Izumi 0623 以社区贡献来源展示，方便玩家区分官方内置和玩家上传内容。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.584",
            "versionCode": 584,
            "releasePublishedAt": "2026-07-09T04:11:13+08:00",
            "releaseNotes": [
                "新增 AI 请求超时设置：玩家可在游戏设定里调整正文、开局、规划、动态世界等请求的等待时间，默认保持 120 秒。",
                "新增开局时间设置：新建存档时可自定义初始年月日时刻，并会同步写入环境时间和天气结束时间。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.567",
            "versionCode": 567,
            "releasePublishedAt": "2026-07-05T18:58:34.483+08:00",
            "releaseNotes": [
                "修复创意工坊本地导入 JSON 没有编辑入口的问题：本地测试的模式包现在可以直接打开完整 JSON 编辑并保存。",
                "修复已发布到社区的本人投稿只能改标题、简介、标签的问题：作者现在可以编辑并保存完整模块 JSON 内容。",
                "完善创意工坊完整模式包保存：payload、contentBlocks、modeWorldbooks、worldDetailGeneration、modeRuntimeProfile 等核心字段会完整保留，减少编辑后实际配置没变的问题。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.566",
            "versionCode": 566,
            "releasePublishedAt": "2026-07-05T18:22:29.806+08:00",
            "releaseNotes": [
                "修复正文对话框偶尔丢失的问题：空角色标签、裸引号对白、对白后混入旁白等格式会退回 AI 重新输出，不再由本地代码强行拼接，减少对话框消失和道友录不同步。",
                "优化临场 NPC 识别：散修首领、护卫、随从、执事等称谓型人物有规范对白时，会进入变量生成复核，减少关键敌人或路人没有社交档案的问题。",
                "修复回合结束提示音过早播放的问题：提示音会等正文、变量生成、动态世界、规划分析、地图更新和最终保存队列全部完成后再响。",
                "修复规划分析未单独配置模型时可能跳过的问题：未启用独立模型时会复用主剧情接口继续执行。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.565",
            "versionCode": 565,
            "releasePublishedAt": "2026-07-05T17:16:19.624+08:00",
            "releaseNotes": [
                "优化自动生图提示词：青竹法剑等灵竹法剑更容易生成青绿色玉竹剑身、竹节纹理和金色护手，减少普通金属剑或错类道具。",
                "修复古代修仙角色图片可能出现现代双肩包的问题：行囊会按古代布包、挎囊或储物袋处理，并加强现代背包负面约束。",
                "优化图片管理器生成队列：生成历史和实时队列合并展示，减少选项卡内空白和重复区域。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.564",
            "versionCode": 564,
            "releasePublishedAt": "2026-07-05T16:13:39+08:00",
            "releaseNotes": [
                "修复正文偶尔混入英文短语的问题：命中后会自动退回 AI 重写为自然中文，而不是把中英夹杂正文落盘。",
                "修复开局重跑时地图数据异常导致“性别比例恢复回合”空指针报错的问题。",
                "修复地图更新阶段偶尔长时间卡住不结束的问题：地图模型请求超时后会自动跳过本轮地图更新并继续完成回合。",
                "增强地图更新诊断日志：记录阶段开始、模型请求、超时、返回、解析命令等边界，方便后续定位卡住位置。",
                "修复判定框只显示“成功”等简短结果的问题：判定值、难度和修正详情会完整展示。",
                "修复同名功法可能显示两遍的问题：同名功法会合并为更高重数的一条记录。",
                "修复主要女性角色私密部位描述为空时后续补图失败的问题：会先自动请求 AI 补齐描述，再继续生成对应图片。",
                "优化符纸、符箓类物品图标提示词：允许不可读朱砂符纹，减少生成成塑料板或空白硬板的情况。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.563",
            "versionCode": 563,
            "releasePublishedAt": "2026-07-05T13:48:01+08:00",
            "releaseNotes": [
                "修复正文偶尔混入英文短语的问题：命中后会自动退回 AI 重写为自然中文，而不是把中英夹杂正文落盘。",
                "修复开局重跑时地图数据异常导致“性别比例恢复回合”空指针报错的问题。",
                "修复地图更新阶段偶尔长时间卡住不结束的问题：地图模型请求超时后会自动跳过本轮地图更新并继续完成回合。",
                "增强地图更新诊断日志：记录阶段开始、模型请求、超时、返回、解析命令等边界，方便后续定位卡住位置。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.562",
            "versionCode": 562,
            "releasePublishedAt": "2026-07-05T13:08:05+08:00",
            "releaseNotes": [
                "修复主剧情正文偶尔出现“极其”等空泛强调词刷屏的问题：命中后会自动退回 AI 重写，而不是把低质量正文落盘。",
                "优化主剧情自动重试提示：正文质量审查失败时会明确要求 AI 用动作、感官、环境压力和可见阻力重写强度表达。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.561",
            "versionCode": 561,
            "releasePublishedAt": "2026-07-05T00:39:51.623+08:00",
            "releaseNotes": [
                "修复创意工坊「小说分解模块」大体积分享包发布失败：遮天、剑来等较大的小说分解 ZIP 在整包上传被 OpenList 拒绝时，会自动切成小分片上传。",
                "修复分片分享包下载导入：应用会自动逐片下载、合并并校验大小与 sha256，避免大包导入时卡住或提示 ZIP 暂不可下载。",
                "优化小说分解工作台数据集切换：章节筛选、分段校对等页面会把「切换数据集」放到内容区最上方，减少被遮挡。",
                "补全并修正部分公开小说分解数据集的空字段，减少世界观规则、人物关系、伏笔线索、章节节奏等字段显示为 0 的情况。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.560",
            "versionCode": 560,
            "releasePublishedAt": "2026-07-04T19:45:48+08:00",
            "releaseNotes": [
                "修复小说分解「AI 补全模式包」失败或无效果的问题：AI 返回的 JSON 会正确解析并合并，不再因为解析包装层误判为缺少字段。",
                "修复《剑来》、仙侠等非末日题材被 AI 补全带成末日丧尸模板的问题：会过滤末日物资、感染区、避难所、幸存者等跨题材污染字段。",
                "修复创意工坊「小说分解模块」下载并导入失败：下载改为官网同源代理 OneDrive/OpenList ZIP，并优先使用直连下载地址，减少“模块 ZIP 暂不可下载”和“导入中卡住”。",
                "修复部分环境启动时报 recordDiagnosticLog 未定义导致应用启动失败的问题。",
                "优化上下文完整性提示：仅在长上下文风险场景启用完整性标记，减少短请求误报和不必要干扰。",
                "修复「正文词汇审查」设置重复定义，开关默认状态与设置页显示更稳定。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.559",
            "versionCode": 559,
            "releasePublishedAt": "2026-07-04T16:24:45+08:00",
            "releaseNotes": [
                "修复创意工坊「小说分解模块」大 ZIP 发布失败：上传链路固定走 OpenList 直连源，避免套 Cloudflare 的公网域名触发上传大小限制。",
                "优化 OneDrive/OpenList 上传失败提示：服务端会返回 OpenList 的 HTTP 状态、code 和 message，方便判断权限、目录或服务端拒绝原因。",
                "恢复小说分解工作台「保存设置」入口：保存按钮改为顶部非遮挡操作条，在数据集、创意工坊、章节筛选、分段校对等页面都能看到。",
                "修复首页在线人数悬浮提示层级过高的问题：打开小说分解工作台和其他独立界面时，不再浮到界面上方。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.558",
            "versionCode": 558,
            "releasePublishedAt": "2026-07-04T15:00:29+08:00",
            "releaseNotes": [
                "修复创意工坊「小说分解模块」大 ZIP 发布与下载：发布改为文件直传，不再把几十 MB ZIP 转成 JSON base64，OneDrive 上传失败时会明确中止，避免生成“ZIP 暂不可下载”的坏投稿。",
                "优化创意工坊移动端操作：创意工坊、数据集、章节筛选、分段校对等页面不再被底部“保存设置”固定层遮挡，下载导入、发布和状态提示更容易操作。",
                "优化创意工坊「小说分解工作台」分段校对布局：工作台接近全屏显示，分段目录、右侧校对区和档案区更充分利用宽屏空间。",
                "核心字段改为横向并排：本组概括、开局已成立事实、前组延续事实同排展示，减少上下滚动，关键信息一屏可见更多。",
                "档案字段更紧凑：角色、势力、地点、物品档案的短字段横向密集排列，关系摘要、状态摘要等长内容保留大文本框，避免空框分行浪费空间。",
                "章节筛选和分段校对默认展开，并以「切换数据集」替代折叠入口，方便在不同小说分解数据集之间切换。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.557",
            "versionCode": 557,
            "releasePublishedAt": "2026-07-04T13:28:45+08:00",
            "releaseNotes": [
                "重做创意工坊「小说分解工作台」布局：工作台接近全屏显示，顶部说明、左侧导航、分段目录和右侧校对区能更充分利用屏幕空间。",
                "优化分段校对体验：角色档案、势力档案等结构化内容默认展开展示，保存按钮固定在当前编辑区底部，减少内容被遮挡。",
                "优化章节筛选体验：章节筛选和分段校对不再提供折叠状态，页面默认展开；原折叠入口改为「切换数据集」，方便在不同小说分解数据集之间切换。",
                "修复日间模式下小说分解工作台可能透出首页文字/水印的问题，浅色主题下阅读和校对更干净。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.555",
            "versionCode": 555,
            "releasePublishedAt": "2026-07-03T21:35:44+08:00",
            "releaseNotes": [
                "修复重新安装或旧开局预设残留官方题材提示词时，开新档会跳过世界观设定、直接进入开局剧情的问题。",
                "优化开局兼容：官方题材口径会自动并入世界观生成要求，保留玩家真正导入的完整手动世界观。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.554",
            "versionCode": 554,
            "releasePublishedAt": "2026-07-03T20:30:37+08:00",
            "releaseNotes": [
                "修复完整模式包开新档会跳过世界观生成的问题：新建存档会先生成/细化世界观，再进入开局剧情。",
                "修复仙侠、无限流等模式包题材口径被误当成手动世界观的问题，重装或重新开局后不再直接刷开局。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.552",
            "versionCode": 552,
            "releasePublishedAt": "2026-07-03T18:45:53+08:00",
            "releaseNotes": [
                "修复重新安装或重新下载后动态世界可能不运行的问题：未单独配置世界演变模型时，会自动复用主剧情接口继续执行世界推演。",
                "修复开局队列“重跑开局”只刷新开局剧情、不重新生成世界观的问题：现在会完整重跑世界观与开局剧情，避免新档只刷开场。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.551",
            "versionCode": 551,
            "releasePublishedAt": "2026-07-01T19:31:49+08:00",
            "releaseNotes": [
                "修复 GitHub 云同步登录配置读取：网页端会自动读取 Worker 运行时 OAuth 配置，减少误显示未配置 Client ID 的情况。",
                "优化主剧情自动重试提示：正文过短会明确提示补足正文，不再误显示成解析失败，重试时会更专注补齐剧情内容。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.548",
            "versionCode": 548,
            "releasePublishedAt": "2026-07-01T01:23:14+08:00",
            "releaseNotes": [
                "Cloud Studio 云端 ComfyUI 教程新增一键复刻入口：玩家可直接打开分享应用点击“复刻”，再按 GPU T4、VS Code 布局和终端启动流程接入自己的后端。",
                "补充 Cloud Studio 资源说明：初次登录绑定腾讯云账号可领 20 核时，每日签到可领 2 核时，T4 GPU 约 1.2 核时/小时，方便玩家估算使用成本。",
                "新增 Cloud Studio 云端 ComfyUI 后端接入：设置页可通过通用自动发现注册表刷新到 Cloud Studio 上报的 8188 后端，并支持云端来源标识。",
                "新增“GPT Image 2 · 仙侠线稿玉版平涂风”NPC 生图预设：适合生成线稿清晰、平涂干净、纸本背景雅致的古风修仙 NPC 半身肖像。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.547",
            "versionCode": 547,
            "releasePublishedAt": "2026-07-01T01:01:33+08:00",
            "releaseNotes": [
                "补充 Cloud Studio 云端 ComfyUI 后端教程：新增从 GitHub 导入、GPU T4、VS Code 布局、终端启动、8188 预览、连接口令和 405 处理说明。",
                "新增 Cloud Studio 云端 ComfyUI 后端接入：设置页可通过通用自动发现注册表刷新到 Cloud Studio 上报的 8188 后端，并支持云端来源标识。",
                "完善 Cloud Studio 后端导入指引：默认推荐 GPU T4、VS Code 布局，并在工作区打开后通过终端运行初始化命令，减少手动配置步骤。",
                "新增“GPT Image 2 · 仙侠线稿玉版平涂风”NPC 生图预设：适合生成线稿清晰、平涂干净、纸本背景雅致的古风修仙 NPC 半身肖像。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.546",
            "versionCode": 546,
            "releasePublishedAt": "2026-07-01T00:57:16+08:00",
            "releaseNotes": [
                "新增 Cloud Studio 云端 ComfyUI 后端接入：设置页可通过通用自动发现注册表刷新到 Cloud Studio 上报的 8188 后端，并支持云端来源标识。",
                "完善 Cloud Studio 后端导入指引：默认推荐 GPU T4、VS Code 布局，并在工作区打开后通过终端运行初始化命令，减少手动配置步骤。",
                "新增“GPT Image 2 · 仙侠线稿玉版平涂风”NPC 生图预设：适合生成线稿清晰、平涂干净、纸本背景雅致的古风修仙 NPC 半身肖像。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.545",
            "versionCode": 545,
            "releasePublishedAt": "2026-06-30T14:29:42.608+08:00",
            "releaseNotes": [
                "修复开局伙伴私密部位图片可能重复生成的问题：已生成成功的图片会正确归档到对应角色，减少重复等待和资源浪费。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.544",
            "versionCode": 544,
            "releasePublishedAt": "2026-06-30T01:31:38+08:00",
            "releaseNotes": [
                "修复 APIMart / GPT Image 2 生图渠道的异步任务解析：支持 task_id 轮询和嵌套图片链接，避免生成完成后仍显示空白。",
                "增强图片保存校验：临时链接返回错误文本时不再误标为成功图片，减少苹果手机浏览器空白图问题。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.538",
            "versionCode": 538,
            "releasePublishedAt": "2026-06-28T22:55:03+08:00",
            "releaseNotes": [
                "APK 下载源从 EdgeOne CDN 切换到 Backblaze B2 原始地址：国内直连下载速度从约 0.6 MB/s 提升到约 11 MB/s，快 17 倍以上。",
                "酒馆预设面板新增「导出当前预设」按钮：调好的预设可直接保存为 JSON 文件，下次换设备或重装后导入即可恢复，不用重新开关配置。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.537",
            "versionCode": 537,
            "releasePublishedAt": "2026-06-28T22:22:36+08:00",
            "releaseNotes": [
                "APK 下载源从 EdgeOne CDN 切换到 Backblaze B2 原始地址：国内直连下载速度从约 0.6 MB/s 提升到约 11 MB/s，快 17 倍以上。",
                "地图生成模型设置支持导出/导入配置文件：配置好的开关、模型名、API 地址和密钥可保存为 JSON，下次有问题可直接导入恢复，免去重新逐项填写的麻烦。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.536",
            "versionCode": 536,
            "releasePublishedAt": "2026-06-28T21:48:07+08:00",
            "releaseNotes": [
                "APK 下载源从 EdgeOne CDN 切换到 Backblaze B2 原始地址：国内直连下载速度从约 0.6 MB/s 提升到约 11 MB/s，快 17 倍以上。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.535",
            "versionCode": 535,
            "releasePublishedAt": "2026-06-28T20:09:39+08:00",
            "releaseNotes": [
                "修复手机端 GitHub OAuth 登录点击后无反应的问题：APK 现在会通过系统浏览器打开 GitHub 授权页，授权完成后自动回到游戏。",
                "修复对象存储云同步识别不到 Backblaze 存档的问题：新增 S3 端点诊断，能区分 CDN 加速域和真正的 Backblaze S3 API 端点，避免只显示 0 个存档。",
                "优化对象存储云同步提示：当云端清单或 saves 目录无法读取时，会显示 manifest、ListObjectsV2、目录前缀等诊断信息，方便快速修正配置。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.533",
            "versionCode": 533,
            "releasePublishedAt": "2026-06-28T16:52:39+08:00",
            "releaseNotes": [
                "修复小说分解工坊发布大型 ZIP 时的 503 错误：大文件自动使用 OneDrive 兜底存储，减少发布失败。",
                "优化大型社区内容的发布稳定性，降低 D1 批量写入限制带来的中断概率。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        "🛠️ 修复 CNB ComfyUI 轮询超时不再误触发重试 + D1 透明分块存储修复创意工坊发布失败",
        {
            "versionName": "1.0.531",
            "versionCode": 531,
            "releasePublishedAt": "2026-06-28T12:07:58+08:00",
            "releaseNotes": [
                "修复教程中心选项卡点击无反应的问题——HTML标签未正确转义导致页面结构被破坏。",
                "修复AI补全模式包时货币层级（currencyTiers）字段未被正确识别的问题——支持字符串和数组格式的自动转换。",
                "优化网站内存占用——存档/删档/回档操作不再一次性加载全部存档到内存，改用逐条流式处理，大幅降低峰值内存。",
                "手机端队列面板新增X关闭按钮，折叠按钮在手机上宽度适配更合理，不再出现无法关闭的情况。",
                "手机端输入框支持多行输入和展开/折叠切换，输入时自动增高，发送键增加间距减少误触。",
                "修复物品价值字段单位歧义导致货币汇率异常（如金子换银子比价偏低）——AI提示词已明确要求使用最低货币单位。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.529",
            "versionCode": 529,
            "releasePublishedAt": "2026-06-28T01:54:08+08:00",
            "releaseNotes": [
                "优化 APK 下载分发：新增 GitHub Release 备用下载通道，并内置多个 GitHub 加速代理地址，APK 端会自动测速选择最快路径。",
                "修复 GitHub Release APK 资产命名，版本包会以 MoRanJiangHu-v版本号.apk 形式发布，便于稳定回溯和代理下载。",
                "更新下载清单：默认保留 B2/官网代理通道，同时加入 GitHub、GitHub 加速和 OneDrive 备用入口，减少大陆无代理环境下下载失败或过慢的情况。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.529。"
            ]
        },
        {
            "versionName": "1.0.528",
            "versionCode": 528,
            "releasePublishedAt": "2026-06-27T23:26:00+08:00",
            "releaseNotes": [
                "修复创意工坊社区贡献发布和查看失败的问题：登录账号后无法发布或浏览社区贡献的模式包和小说分解内容，根因为认证接口读取了错误的 D1 数据表，现已从正确的用户注册表认证。",
                "修复小说分解分享 ZIP 下载可能返回空文件的问题：D1 存储后端无法返回二进制流，下载时检测并从文本内容重建 ZIP 二进制。",
                "新增小说分解 AI 补全模式包功能：从小说分解数据集自动生成专属的货币、能力体系、组织、地图、NPC、生图口径和开局配置，生成本地模式包或贡献社区模式包时可自动携带 AI 补全的个性化设置。",
                "修复 AI 回合中势力名称被占位名覆盖的问题：AI 部分变量更新可能把真实势力名替换为势力1等占位名，系统现在自动从回合前的真实数据中恢复势力名和功法名，避免名称丢失。",
                "修复图片管理器中未生成图片错误显示为成功的问题：无生成状态的记录现在正确显示为未生成（灰色标签），统计计数不再把未生成图片计入成功数。",
                "修复社交面板无法显示失败或进行中图片状态的问题：当图片生成失败或进行中时，UI 现在能正确显示对应状态而非默认隐藏。",
                "修复 APK 端 NovelAI 图片生成结果为空的问题：改用 Capacitor 原生 HTTP 插件发送二进制请求，避免 Capacitor 劫持 XHR 后 arraybuffer 支持不完整导致的 ZIP 响应截断。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.527",
            "versionCode": 527,
            "releasePublishedAt": "2026-06-27T10:26:00+08:00",
            "releaseNotes": [
                "新增 API 上下文完整性校验：自动检测第三方 API 是否静默截断消息上下文，并在控制台输出警告，帮助排查「AI 失忆」问题。",
                "修复 Android APK 上 NovelAI 图片生成连接失败的问题：Capacitor 原生 HTTP 会损坏 ZIP 二进制响应，改用 XHR 绕过以正确处理图片数据。",
                "修复自定义境界体系不生效、开局后仍显示默认「开脉境/聚息境」的问题：自定义境界的九阶命名、能力边界和终点文案现在正确生成；开局世界观生成流程也正确传入手动境界提示词。",
                "官网：https://msjh.bacon159.pp.ua/"
            ]
        },
        {
            "versionName": "1.0.525",
            "versionCode": 525,
            "releasePublishedAt": "2026-06-25T23:50:39+08:00",
            "releaseNotes": [
                "修复导入酒馆预设后原有提示词被项目默认风格/格式/字数/免责声明覆盖的问题：酒馆模式下外部预设完全主导提示词，不再混入本项目协议。",
                "修复正常着装和普通场景被生图 API 误判为色情内容的问题：非 NSFW 模式下自动过滤成人敏感标签，只有明确开启 NSFW 时才保留。",
                "新增 Izumi 0623 作为内置酒馆预设，支持直接导入使用。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web 与更新清单到 v1.0.525。"
            ]
        },
        {
            "versionName": "1.0.524",
            "versionCode": 524,
            "releasePublishedAt": "2026-06-25T01:55:30+08:00",
            "releaseNotes": [
                "修复开局、正文优化和变量生成链路对玩家额外提示词的执行优先级：禁名、新文风、人物塑造等长期设置会作为最高优先级规则持续生效，减少更新后被默认思维链覆盖的情况。",
                "备用 APK 下载渠道从 Cloudflare R2 二进制备用线路切换为 B2/Cloudflare 缓存线路；更新清单继续保留 hi168 首选，并提供 B2 作为备用下载。",
                "优化 APK 下载地址探测排序：测速差距不明显时保持清单顺序，避免备用线路因短暂 HEAD 响应误抢首选下载。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.524。"
            ]
        },
        {
            "versionName": "1.0.523",
            "versionCode": 523,
            "releasePublishedAt": "2026-06-24T18:08:21.572+08:00",
            "releaseNotes": [
                "修复正文变量生成后，部分 NPC 档案字段没有稳定写入表格的问题：同一角色的补充资料会合并进现有档案，不再漏填。",
                "修复已存在角色可能被部分变量覆盖后显示成“角色1”的问题：角色姓名、简介、记忆和既有档案会被保留。",
                "优化角色档案补全逻辑：胸部、小穴、屁穴等补充描述会优先采用最新生成内容，同时保留原有角色身份信息。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.523。"
            ]
        },
        {
            "versionName": "1.0.522",
            "versionCode": 522,
            "releasePublishedAt": "2026-06-24T01:47:21+08:00",
            "releaseNotes": [
                "修复开局初始化队列中部分阶段后开启时点击重新生成没有反应的问题：现在开局队列会明确重跑开局流程，不再出现空点击。",
                "修复开局女伙伴 NPC 头像可能重复生成的问题：早期开局生图结果会正确写回后续角色档案，避免同一伙伴头像重复排队。",
                "优化图册生产队列滚动体验：队列滚到底后不再继续带动外层页面空滚。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.522。"
            ]
        },
        {
            "versionName": "1.0.521",
            "versionCode": 521,
            "releasePublishedAt": "2026-06-23T23:35:41+08:00",
            "releaseNotes": [
                "修复开局刚生成完成后立刻保存、再次读档可能只剩“正在生成开场内容”的问题：现在会从存档记忆中恢复开局正文，避免新档读入后主内容空白。",
                "修复私密部位特写生图被普通角色、胸部、头像、服装或 CG 画风提示词带偏的问题：部位特写会隔离普通 NPC 画师串，并过滤错误部位与人像词。",
                "优化自动生图提示词：写实画风不再被 GPT Image 2 默认 CG 转化器强制覆盖，场景图也减少误生成人物大头和残留中文提示词的问题。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.521。"
            ]
        }
    ],
    "websiteUrl": "https://msjh.bacon159.pp.ua",
    "githubRepoUrl": "https://github.com/ypq123456789/MoRanJiangHu",
    "cnbGuideUrl": "https://msjh.bacon159.pp.ua/tutorials.html#comfy",
    "releaseNotesUrl": "https://msjh.bacon159.pp.ua/changelog.html",
    "apkDownloadUrl": "https://msjh.bacon159.pp.ua/api/apk/latest.apk",
    "updateManifestUrl": "https://msjh.bacon159.pp.ua/api/apk/latest.json",
    "r2Bucket": "quark-downloads-bacon",
    "r2Prefix": "moranjianghu",
    "backupWebsiteUrl": "https://msjh.bacon.de5.net",
    "multiDeviceSyncGuideUrl": "https://msjh.bacon159.pp.ua/tutorials.html#sync",
    "tutorialsUrl": "https://msjh.bacon159.pp.ua/tutorials.html",
    "changes": [
        "修复部分 AI 渠道“思考中”时间稍长就被误判为连接超时的问题：AI 出正文前的分析思考阶段不再计入超时等待，正文会正常继续输出，不会中途断开。",
        "修复从商店、任务或 NPC 手中获得的「货币类」物品（如通用流通货币、银票、灵晶等）只能占着背包、无法花出去的问题：这类物品现在可以在背包里一键兑换为对应金钱入账。",
        "修复在手机 App 里导出小说或分解分享包后提示“已保存”却在文件管理器里找不到的问题：导出时会弹出系统分享面板，可直接保存到手机文件、发送到微信或网盘。",
        "修复大型存档读取较慢时界面长时间没有反馈、容易误以为卡死的问题：读取超过一定时间会显示“正在恢复存档状态，请耐心等待”的提示。",
        "官网：https://msjh.bacon159.pp.ua/",
        "备用站：https://msjh.bacon.de5.net/"
    ],
    "notes": "修复部分 AI 渠道“思考中”时间稍长就被误判为连接超时的问题：AI 出正文前的分析思考阶段不再计入超时等待，正文会正常继续输出，不会中途断开。\n修复从商店、任务或 NPC 手中获得的「货币类」物品（如通用流通货币、银票、灵晶等）只能占着背包、无法花出去的问题：这类物品现在可以在背包里一键兑换为对应金钱入账。\n修复在手机 App 里导出小说或分解分享包后提示“已保存”却在文件管理器里找不到的问题：导出时会弹出系统分享面板，可直接保存到手机文件、发送到微信或网盘。\n修复大型存档读取较慢时界面长时间没有反馈、容易误以为卡死的问题：读取超过一定时间会显示“正在恢复存档状态，请耐心等待”的提示。\n官网：https://msjh.bacon159.pp.ua/\n备用站：https://msjh.bacon.de5.net/",
    "releasePublishedAt": "2026-09-05T11:36:10+08:00"
} as const;

export type ReleaseInfo = typeof RELEASE_INFO;
