// Auto-generated by scripts/sync-release.mjs. Do not edit manually.
export const RELEASE_INFO = {
    "versionCode": 2,
    "versionName": "1.0.1",
    "releaseChannel": "stable",
    "websiteUrl": "https://msjh.bacon.de5.net",
    "githubRepoUrl": "https://github.com/ypq123456789/MoRanJiangHu",
    "releaseNotesUrl": "https://github.com/ypq123456789/MoRanJiangHu/commits/main",
    "apkDownloadUrl": "https://download.bacon.de5.net/moranjianghu/latest.apk",
    "updateManifestUrl": "https://download.bacon.de5.net/moranjianghu/latest.json",
    "r2Bucket": "quark-downloads-bacon",
    "r2Prefix": "moranjianghu"
} as const;

export type ReleaseInfo = typeof RELEASE_INFO;
