// Auto-generated by scripts/sync-release.mjs. Do not edit manually.
export const RELEASE_INFO = {
    "versionCode": 571,
    "versionName": "1.0.571",
    "releaseChannel": "stable",
    "releaseNotes": [
        "修复酒馆双人成行等预设首回合反复超时重试的问题：正文和 A/B/C/D 选项已经完整生成时会正确落盘，不再因 <branches> 格式误判失败。",
        "优化酒馆预设兼容：启用酒馆模式后由外部预设主导文风、格式、COT 和字数要求，不再混入项目内置写作提示。",
        "修复环境、状态、装备等机制标签被误识别成人名并渲染成对话框的问题：疑似错误标签会交给 AI 局部确认修正。",
        "修复创意工坊小说分解大 ZIP 上传失败时的多入口重试，提升大型分享包发布成功率。",
        "优化日式四字姓名识别，减少正常角色名在正文对白中丢失的问题。",
        "官网：https://msjh.bacon159.pp.ua/",
        "备用站：https://msjh.bacon.de5.net/"
    ],
    "releaseHistory": [
        {
            "versionName": "1.0.567",
            "versionCode": 567,
            "releasePublishedAt": "2026-07-05T18:58:34.483+08:00",
            "releaseNotes": [
                "修复创意工坊本地导入 JSON 没有编辑入口的问题：本地测试的模式包现在可以直接打开完整 JSON 编辑并保存。",
                "修复已发布到社区的本人投稿只能改标题、简介、标签的问题：作者现在可以编辑并保存完整模块 JSON 内容。",
                "完善创意工坊完整模式包保存：payload、contentBlocks、modeWorldbooks、worldDetailGeneration、modeRuntimeProfile 等核心字段会完整保留，减少编辑后实际配置没变的问题。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.566",
            "versionCode": 566,
            "releasePublishedAt": "2026-07-05T18:22:29.806+08:00",
            "releaseNotes": [
                "修复正文对话框偶尔丢失的问题：空角色标签、裸引号对白、对白后混入旁白等格式会退回 AI 重新输出，不再由本地代码强行拼接，减少对话框消失和道友录不同步。",
                "优化临场 NPC 识别：散修首领、护卫、随从、执事等称谓型人物有规范对白时，会进入变量生成复核，减少关键敌人或路人没有社交档案的问题。",
                "修复回合结束提示音过早播放的问题：提示音会等正文、变量生成、动态世界、规划分析、地图更新和最终保存队列全部完成后再响。",
                "修复规划分析未单独配置模型时可能跳过的问题：未启用独立模型时会复用主剧情接口继续执行。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.565",
            "versionCode": 565,
            "releasePublishedAt": "2026-07-05T17:16:19.624+08:00",
            "releaseNotes": [
                "优化自动生图提示词：青竹法剑等灵竹法剑更容易生成青绿色玉竹剑身、竹节纹理和金色护手，减少普通金属剑或错类道具。",
                "修复古代修仙角色图片可能出现现代双肩包的问题：行囊会按古代布包、挎囊或储物袋处理，并加强现代背包负面约束。",
                "优化图片管理器生成队列：生成历史和实时队列合并展示，减少选项卡内空白和重复区域。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.564",
            "versionCode": 564,
            "releasePublishedAt": "2026-07-05T16:13:39+08:00",
            "releaseNotes": [
                "修复正文偶尔混入英文短语的问题：命中后会自动退回 AI 重写为自然中文，而不是把中英夹杂正文落盘。",
                "修复开局重跑时地图数据异常导致“性别比例恢复回合”空指针报错的问题。",
                "修复地图更新阶段偶尔长时间卡住不结束的问题：地图模型请求超时后会自动跳过本轮地图更新并继续完成回合。",
                "增强地图更新诊断日志：记录阶段开始、模型请求、超时、返回、解析命令等边界，方便后续定位卡住位置。",
                "修复判定框只显示“成功”等简短结果的问题：判定值、难度和修正详情会完整展示。",
                "修复同名功法可能显示两遍的问题：同名功法会合并为更高重数的一条记录。",
                "修复主要女性角色私密部位描述为空时后续补图失败的问题：会先自动请求 AI 补齐描述，再继续生成对应图片。",
                "优化符纸、符箓类物品图标提示词：允许不可读朱砂符纹，减少生成成塑料板或空白硬板的情况。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.563",
            "versionCode": 563,
            "releasePublishedAt": "2026-07-05T13:48:01+08:00",
            "releaseNotes": [
                "修复正文偶尔混入英文短语的问题：命中后会自动退回 AI 重写为自然中文，而不是把中英夹杂正文落盘。",
                "修复开局重跑时地图数据异常导致“性别比例恢复回合”空指针报错的问题。",
                "修复地图更新阶段偶尔长时间卡住不结束的问题：地图模型请求超时后会自动跳过本轮地图更新并继续完成回合。",
                "增强地图更新诊断日志：记录阶段开始、模型请求、超时、返回、解析命令等边界，方便后续定位卡住位置。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.562",
            "versionCode": 562,
            "releasePublishedAt": "2026-07-05T13:08:05+08:00",
            "releaseNotes": [
                "修复主剧情正文偶尔出现“极其”等空泛强调词刷屏的问题：命中后会自动退回 AI 重写，而不是把低质量正文落盘。",
                "优化主剧情自动重试提示：正文质量审查失败时会明确要求 AI 用动作、感官、环境压力和可见阻力重写强度表达。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.561",
            "versionCode": 561,
            "releasePublishedAt": "2026-07-05T00:39:51.623+08:00",
            "releaseNotes": [
                "修复创意工坊「小说分解模块」大体积分享包发布失败：遮天、剑来等较大的小说分解 ZIP 在整包上传被 OpenList 拒绝时，会自动切成小分片上传。",
                "修复分片分享包下载导入：应用会自动逐片下载、合并并校验大小与 sha256，避免大包导入时卡住或提示 ZIP 暂不可下载。",
                "优化小说分解工作台数据集切换：章节筛选、分段校对等页面会把「切换数据集」放到内容区最上方，减少被遮挡。",
                "补全并修正部分公开小说分解数据集的空字段，减少世界观规则、人物关系、伏笔线索、章节节奏等字段显示为 0 的情况。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.560",
            "versionCode": 560,
            "releasePublishedAt": "2026-07-04T19:45:48+08:00",
            "releaseNotes": [
                "修复小说分解「AI 补全模式包」失败或无效果的问题：AI 返回的 JSON 会正确解析并合并，不再因为解析包装层误判为缺少字段。",
                "修复《剑来》、仙侠等非末日题材被 AI 补全带成末日丧尸模板的问题：会过滤末日物资、感染区、避难所、幸存者等跨题材污染字段。",
                "修复创意工坊「小说分解模块」下载并导入失败：下载改为官网同源代理 OneDrive/OpenList ZIP，并优先使用直连下载地址，减少“模块 ZIP 暂不可下载”和“导入中卡住”。",
                "修复部分环境启动时报 recordDiagnosticLog 未定义导致应用启动失败的问题。",
                "优化上下文完整性提示：仅在长上下文风险场景启用完整性标记，减少短请求误报和不必要干扰。",
                "修复「正文词汇审查」设置重复定义，开关默认状态与设置页显示更稳定。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.559",
            "versionCode": 559,
            "releasePublishedAt": "2026-07-04T16:24:45+08:00",
            "releaseNotes": [
                "修复创意工坊「小说分解模块」大 ZIP 发布失败：上传链路固定走 OpenList 直连源，避免套 Cloudflare 的公网域名触发上传大小限制。",
                "优化 OneDrive/OpenList 上传失败提示：服务端会返回 OpenList 的 HTTP 状态、code 和 message，方便判断权限、目录或服务端拒绝原因。",
                "恢复小说分解工作台「保存设置」入口：保存按钮改为顶部非遮挡操作条，在数据集、创意工坊、章节筛选、分段校对等页面都能看到。",
                "修复首页在线人数悬浮提示层级过高的问题：打开小说分解工作台和其他独立界面时，不再浮到界面上方。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.558",
            "versionCode": 558,
            "releasePublishedAt": "2026-07-04T15:00:29+08:00",
            "releaseNotes": [
                "修复创意工坊「小说分解模块」大 ZIP 发布与下载：发布改为文件直传，不再把几十 MB ZIP 转成 JSON base64，OneDrive 上传失败时会明确中止，避免生成“ZIP 暂不可下载”的坏投稿。",
                "优化创意工坊移动端操作：创意工坊、数据集、章节筛选、分段校对等页面不再被底部“保存设置”固定层遮挡，下载导入、发布和状态提示更容易操作。",
                "优化创意工坊「小说分解工作台」分段校对布局：工作台接近全屏显示，分段目录、右侧校对区和档案区更充分利用宽屏空间。",
                "核心字段改为横向并排：本组概括、开局已成立事实、前组延续事实同排展示，减少上下滚动，关键信息一屏可见更多。",
                "档案字段更紧凑：角色、势力、地点、物品档案的短字段横向密集排列，关系摘要、状态摘要等长内容保留大文本框，避免空框分行浪费空间。",
                "章节筛选和分段校对默认展开，并以「切换数据集」替代折叠入口，方便在不同小说分解数据集之间切换。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.557",
            "versionCode": 557,
            "releasePublishedAt": "2026-07-04T13:28:45+08:00",
            "releaseNotes": [
                "重做创意工坊「小说分解工作台」布局：工作台接近全屏显示，顶部说明、左侧导航、分段目录和右侧校对区能更充分利用屏幕空间。",
                "优化分段校对体验：角色档案、势力档案等结构化内容默认展开展示，保存按钮固定在当前编辑区底部，减少内容被遮挡。",
                "优化章节筛选体验：章节筛选和分段校对不再提供折叠状态，页面默认展开；原折叠入口改为「切换数据集」，方便在不同小说分解数据集之间切换。",
                "修复日间模式下小说分解工作台可能透出首页文字/水印的问题，浅色主题下阅读和校对更干净。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.555",
            "versionCode": 555,
            "releasePublishedAt": "2026-07-03T21:35:44+08:00",
            "releaseNotes": [
                "修复重新安装或旧开局预设残留官方题材提示词时，开新档会跳过世界观设定、直接进入开局剧情的问题。",
                "优化开局兼容：官方题材口径会自动并入世界观生成要求，保留玩家真正导入的完整手动世界观。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.554",
            "versionCode": 554,
            "releasePublishedAt": "2026-07-03T20:30:37+08:00",
            "releaseNotes": [
                "修复完整模式包开新档会跳过世界观生成的问题：新建存档会先生成/细化世界观，再进入开局剧情。",
                "修复仙侠、无限流等模式包题材口径被误当成手动世界观的问题，重装或重新开局后不再直接刷开局。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.552",
            "versionCode": 552,
            "releasePublishedAt": "2026-07-03T18:45:53+08:00",
            "releaseNotes": [
                "修复重新安装或重新下载后动态世界可能不运行的问题：未单独配置世界演变模型时，会自动复用主剧情接口继续执行世界推演。",
                "修复开局队列“重跑开局”只刷新开局剧情、不重新生成世界观的问题：现在会完整重跑世界观与开局剧情，避免新档只刷开场。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.551",
            "versionCode": 551,
            "releasePublishedAt": "2026-07-01T19:31:49+08:00",
            "releaseNotes": [
                "修复 GitHub 云同步登录配置读取：网页端会自动读取 Worker 运行时 OAuth 配置，减少误显示未配置 Client ID 的情况。",
                "优化主剧情自动重试提示：正文过短会明确提示补足正文，不再误显示成解析失败，重试时会更专注补齐剧情内容。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.548",
            "versionCode": 548,
            "releasePublishedAt": "2026-07-01T01:23:14+08:00",
            "releaseNotes": [
                "Cloud Studio 云端 ComfyUI 教程新增一键复刻入口：玩家可直接打开分享应用点击“复刻”，再按 GPU T4、VS Code 布局和终端启动流程接入自己的后端。",
                "补充 Cloud Studio 资源说明：初次登录绑定腾讯云账号可领 20 核时，每日签到可领 2 核时，T4 GPU 约 1.2 核时/小时，方便玩家估算使用成本。",
                "新增 Cloud Studio 云端 ComfyUI 后端接入：设置页可通过通用自动发现注册表刷新到 Cloud Studio 上报的 8188 后端，并支持云端来源标识。",
                "新增“GPT Image 2 · 仙侠线稿玉版平涂风”NPC 生图预设：适合生成线稿清晰、平涂干净、纸本背景雅致的古风修仙 NPC 半身肖像。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.547",
            "versionCode": 547,
            "releasePublishedAt": "2026-07-01T01:01:33+08:00",
            "releaseNotes": [
                "补充 Cloud Studio 云端 ComfyUI 后端教程：新增从 GitHub 导入、GPU T4、VS Code 布局、终端启动、8188 预览、连接口令和 405 处理说明。",
                "新增 Cloud Studio 云端 ComfyUI 后端接入：设置页可通过通用自动发现注册表刷新到 Cloud Studio 上报的 8188 后端，并支持云端来源标识。",
                "完善 Cloud Studio 后端导入指引：默认推荐 GPU T4、VS Code 布局，并在工作区打开后通过终端运行初始化命令，减少手动配置步骤。",
                "新增“GPT Image 2 · 仙侠线稿玉版平涂风”NPC 生图预设：适合生成线稿清晰、平涂干净、纸本背景雅致的古风修仙 NPC 半身肖像。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.546",
            "versionCode": 546,
            "releasePublishedAt": "2026-07-01T00:57:16+08:00",
            "releaseNotes": [
                "新增 Cloud Studio 云端 ComfyUI 后端接入：设置页可通过通用自动发现注册表刷新到 Cloud Studio 上报的 8188 后端，并支持云端来源标识。",
                "完善 Cloud Studio 后端导入指引：默认推荐 GPU T4、VS Code 布局，并在工作区打开后通过终端运行初始化命令，减少手动配置步骤。",
                "新增“GPT Image 2 · 仙侠线稿玉版平涂风”NPC 生图预设：适合生成线稿清晰、平涂干净、纸本背景雅致的古风修仙 NPC 半身肖像。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.545",
            "versionCode": 545,
            "releasePublishedAt": "2026-06-30T14:29:42.608+08:00",
            "releaseNotes": [
                "修复开局伙伴私密部位图片可能重复生成的问题：已生成成功的图片会正确归档到对应角色，减少重复等待和资源浪费。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.544",
            "versionCode": 544,
            "releasePublishedAt": "2026-06-30T01:31:38+08:00",
            "releaseNotes": [
                "修复 APIMart / GPT Image 2 生图渠道的异步任务解析：支持 task_id 轮询和嵌套图片链接，避免生成完成后仍显示空白。",
                "增强图片保存校验：临时链接返回错误文本时不再误标为成功图片，减少苹果手机浏览器空白图问题。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.538",
            "versionCode": 538,
            "releasePublishedAt": "2026-06-28T22:55:03+08:00",
            "releaseNotes": [
                "APK 下载源从 EdgeOne CDN 切换到 Backblaze B2 原始地址：国内直连下载速度从约 0.6 MB/s 提升到约 11 MB/s，快 17 倍以上。",
                "酒馆预设面板新增「导出当前预设」按钮：调好的预设可直接保存为 JSON 文件，下次换设备或重装后导入即可恢复，不用重新开关配置。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.537",
            "versionCode": 537,
            "releasePublishedAt": "2026-06-28T22:22:36+08:00",
            "releaseNotes": [
                "APK 下载源从 EdgeOne CDN 切换到 Backblaze B2 原始地址：国内直连下载速度从约 0.6 MB/s 提升到约 11 MB/s，快 17 倍以上。",
                "地图生成模型设置支持导出/导入配置文件：配置好的开关、模型名、API 地址和密钥可保存为 JSON，下次有问题可直接导入恢复，免去重新逐项填写的麻烦。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.536",
            "versionCode": 536,
            "releasePublishedAt": "2026-06-28T21:48:07+08:00",
            "releaseNotes": [
                "APK 下载源从 EdgeOne CDN 切换到 Backblaze B2 原始地址：国内直连下载速度从约 0.6 MB/s 提升到约 11 MB/s，快 17 倍以上。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.535",
            "versionCode": 535,
            "releasePublishedAt": "2026-06-28T20:09:39+08:00",
            "releaseNotes": [
                "修复手机端 GitHub OAuth 登录点击后无反应的问题：APK 现在会通过系统浏览器打开 GitHub 授权页，授权完成后自动回到游戏。",
                "修复对象存储云同步识别不到 Backblaze 存档的问题：新增 S3 端点诊断，能区分 CDN 加速域和真正的 Backblaze S3 API 端点，避免只显示 0 个存档。",
                "优化对象存储云同步提示：当云端清单或 saves 目录无法读取时，会显示 manifest、ListObjectsV2、目录前缀等诊断信息，方便快速修正配置。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.533",
            "versionCode": 533,
            "releasePublishedAt": "2026-06-28T16:52:39+08:00",
            "releaseNotes": [
                "修复小说分解工坊发布大型 ZIP 时的 503 错误：大文件自动使用 OneDrive 兜底存储，减少发布失败。",
                "优化大型社区内容的发布稳定性，降低 D1 批量写入限制带来的中断概率。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        "🛠️ 修复 CNB ComfyUI 轮询超时不再误触发重试 + D1 透明分块存储修复创意工坊发布失败",
        {
            "versionName": "1.0.531",
            "versionCode": 531,
            "releasePublishedAt": "2026-06-28T12:07:58+08:00",
            "releaseNotes": [
                "修复教程中心选项卡点击无反应的问题——HTML标签未正确转义导致页面结构被破坏。",
                "修复AI补全模式包时货币层级（currencyTiers）字段未被正确识别的问题——支持字符串和数组格式的自动转换。",
                "优化网站内存占用——存档/删档/回档操作不再一次性加载全部存档到内存，改用逐条流式处理，大幅降低峰值内存。",
                "手机端队列面板新增X关闭按钮，折叠按钮在手机上宽度适配更合理，不再出现无法关闭的情况。",
                "手机端输入框支持多行输入和展开/折叠切换，输入时自动增高，发送键增加间距减少误触。",
                "修复物品价值字段单位歧义导致货币汇率异常（如金子换银子比价偏低）——AI提示词已明确要求使用最低货币单位。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.529",
            "versionCode": 529,
            "releasePublishedAt": "2026-06-28T01:54:08+08:00",
            "releaseNotes": [
                "优化 APK 下载分发：新增 GitHub Release 备用下载通道，并内置多个 GitHub 加速代理地址，APK 端会自动测速选择最快路径。",
                "修复 GitHub Release APK 资产命名，版本包会以 MoRanJiangHu-v版本号.apk 形式发布，便于稳定回溯和代理下载。",
                "更新下载清单：默认保留 B2/官网代理通道，同时加入 GitHub、GitHub 加速和 OneDrive 备用入口，减少大陆无代理环境下下载失败或过慢的情况。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.529。"
            ]
        },
        {
            "versionName": "1.0.528",
            "versionCode": 528,
            "releasePublishedAt": "2026-06-27T23:26:00+08:00",
            "releaseNotes": [
                "修复创意工坊社区贡献发布和查看失败的问题：登录账号后无法发布或浏览社区贡献的模式包和小说分解内容，根因为认证接口读取了错误的 D1 数据表，现已从正确的用户注册表认证。",
                "修复小说分解分享 ZIP 下载可能返回空文件的问题：D1 存储后端无法返回二进制流，下载时检测并从文本内容重建 ZIP 二进制。",
                "新增小说分解 AI 补全模式包功能：从小说分解数据集自动生成专属的货币、能力体系、组织、地图、NPC、生图口径和开局配置，生成本地模式包或贡献社区模式包时可自动携带 AI 补全的个性化设置。",
                "修复 AI 回合中势力名称被占位名覆盖的问题：AI 部分变量更新可能把真实势力名替换为势力1等占位名，系统现在自动从回合前的真实数据中恢复势力名和功法名，避免名称丢失。",
                "修复图片管理器中未生成图片错误显示为成功的问题：无生成状态的记录现在正确显示为未生成（灰色标签），统计计数不再把未生成图片计入成功数。",
                "修复社交面板无法显示失败或进行中图片状态的问题：当图片生成失败或进行中时，UI 现在能正确显示对应状态而非默认隐藏。",
                "修复 APK 端 NovelAI 图片生成结果为空的问题：改用 Capacitor 原生 HTTP 插件发送二进制请求，避免 Capacitor 劫持 XHR 后 arraybuffer 支持不完整导致的 ZIP 响应截断。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/"
            ]
        },
        {
            "versionName": "1.0.527",
            "versionCode": 527,
            "releasePublishedAt": "2026-06-27T10:26:00+08:00",
            "releaseNotes": [
                "新增 API 上下文完整性校验：自动检测第三方 API 是否静默截断消息上下文，并在控制台输出警告，帮助排查「AI 失忆」问题。",
                "修复 Android APK 上 NovelAI 图片生成连接失败的问题：Capacitor 原生 HTTP 会损坏 ZIP 二进制响应，改用 XHR 绕过以正确处理图片数据。",
                "修复自定义境界体系不生效、开局后仍显示默认「开脉境/聚息境」的问题：自定义境界的九阶命名、能力边界和终点文案现在正确生成；开局世界观生成流程也正确传入手动境界提示词。",
                "官网：https://msjh.bacon159.pp.ua/"
            ]
        },
        {
            "versionName": "1.0.525",
            "versionCode": 525,
            "releasePublishedAt": "2026-06-25T23:50:39+08:00",
            "releaseNotes": [
                "修复导入酒馆预设后原有提示词被项目默认风格/格式/字数/免责声明覆盖的问题：酒馆模式下外部预设完全主导提示词，不再混入本项目协议。",
                "修复正常着装和普通场景被生图 API 误判为色情内容的问题：非 NSFW 模式下自动过滤成人敏感标签，只有明确开启 NSFW 时才保留。",
                "新增 Izumi 0623 作为内置酒馆预设，支持直接导入使用。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web 与更新清单到 v1.0.525。"
            ]
        },
        {
            "versionName": "1.0.524",
            "versionCode": 524,
            "releasePublishedAt": "2026-06-25T01:55:30+08:00",
            "releaseNotes": [
                "修复开局、正文优化和变量生成链路对玩家额外提示词的执行优先级：禁名、新文风、人物塑造等长期设置会作为最高优先级规则持续生效，减少更新后被默认思维链覆盖的情况。",
                "备用 APK 下载渠道从 Cloudflare R2 二进制备用线路切换为 B2/Cloudflare 缓存线路；更新清单继续保留 hi168 首选，并提供 B2 作为备用下载。",
                "优化 APK 下载地址探测排序：测速差距不明显时保持清单顺序，避免备用线路因短暂 HEAD 响应误抢首选下载。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.524。"
            ]
        },
        {
            "versionName": "1.0.523",
            "versionCode": 523,
            "releasePublishedAt": "2026-06-24T18:08:21.572+08:00",
            "releaseNotes": [
                "修复正文变量生成后，部分 NPC 档案字段没有稳定写入表格的问题：同一角色的补充资料会合并进现有档案，不再漏填。",
                "修复已存在角色可能被部分变量覆盖后显示成“角色1”的问题：角色姓名、简介、记忆和既有档案会被保留。",
                "优化角色档案补全逻辑：胸部、小穴、屁穴等补充描述会优先采用最新生成内容，同时保留原有角色身份信息。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.523。"
            ]
        },
        {
            "versionName": "1.0.522",
            "versionCode": 522,
            "releasePublishedAt": "2026-06-24T01:47:21+08:00",
            "releaseNotes": [
                "修复开局初始化队列中部分阶段后开启时点击重新生成没有反应的问题：现在开局队列会明确重跑开局流程，不再出现空点击。",
                "修复开局女伙伴 NPC 头像可能重复生成的问题：早期开局生图结果会正确写回后续角色档案，避免同一伙伴头像重复排队。",
                "优化图册生产队列滚动体验：队列滚到底后不再继续带动外层页面空滚。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.522。"
            ]
        },
        {
            "versionName": "1.0.521",
            "versionCode": 521,
            "releasePublishedAt": "2026-06-23T23:35:41+08:00",
            "releaseNotes": [
                "修复开局刚生成完成后立刻保存、再次读档可能只剩“正在生成开场内容”的问题：现在会从存档记忆中恢复开局正文，避免新档读入后主内容空白。",
                "修复私密部位特写生图被普通角色、胸部、头像、服装或 CG 画风提示词带偏的问题：部位特写会隔离普通 NPC 画师串，并过滤错误部位与人像词。",
                "优化自动生图提示词：写实画风不再被 GPT Image 2 默认 CG 转化器强制覆盖，场景图也减少误生成人物大头和残留中文提示词的问题。",
                "官网：https://msjh.bacon159.pp.ua/",
                "备用站：https://msjh.bacon.de5.net/",
                "同步更新 Web、APK 与更新清单到 v1.0.521。"
            ]
        }
    ],
    "websiteUrl": "https://msjh.bacon159.pp.ua",
    "githubRepoUrl": "https://github.com/ypq123456789/MoRanJiangHu",
    "cnbGuideUrl": "https://msjh.bacon159.pp.ua/tutorials.html#comfy",
    "releaseNotesUrl": "https://msjh.bacon159.pp.ua/changelog.html",
    "b2CdnBaseUrl": "https://cdn.bacon159.pp.ua",
    "apkDownloadUrl": "https://msjh.bacon159.pp.ua/api/apk/latest.apk",
    "updateManifestUrl": "https://msjh.bacon159.pp.ua/api/apk/latest.json",
    "r2Bucket": "quark-downloads-bacon",
    "r2Prefix": "moranjianghu",
    "backupWebsiteUrl": "https://msjh.bacon.de5.net",
    "multiDeviceSyncGuideUrl": "https://msjh.bacon159.pp.ua/tutorials.html#sync",
    "tutorialsUrl": "https://msjh.bacon159.pp.ua/tutorials.html",
    "changes": [
        "修复酒馆双人成行等预设首回合反复超时重试的问题：正文和 A/B/C/D 选项已经完整生成时会正确落盘，不再因 <branches> 格式误判失败。",
        "优化酒馆预设兼容：启用酒馆模式后由外部预设主导文风、格式、COT 和字数要求，不再混入项目内置写作提示。",
        "修复环境、状态、装备等机制标签被误识别成人名并渲染成对话框的问题：疑似错误标签会交给 AI 局部确认修正。",
        "修复创意工坊小说分解大 ZIP 上传失败时的多入口重试，提升大型分享包发布成功率。",
        "优化日式四字姓名识别，减少正常角色名在正文对白中丢失的问题。",
        "官网：https://msjh.bacon159.pp.ua/",
        "备用站：https://msjh.bacon.de5.net/"
    ],
    "notes": "修复酒馆双人成行等预设首回合反复超时重试的问题：正文和 A/B/C/D 选项已经完整生成时会正确落盘，不再因 <branches> 格式误判失败。\n优化酒馆预设兼容：启用酒馆模式后由外部预设主导文风、格式、COT 和字数要求，不再混入项目内置写作提示。\n修复环境、状态、装备等机制标签被误识别成人名并渲染成对话框的问题：疑似错误标签会交给 AI 局部确认修正。\n修复创意工坊小说分解大 ZIP 上传失败时的多入口重试，提升大型分享包发布成功率。\n优化日式四字姓名识别，减少正常角色名在正文对白中丢失的问题。\n官网：https://msjh.bacon159.pp.ua/\n备用站：https://msjh.bacon.de5.net/",
    "releasePublishedAt": "2026-07-06T12:22:12+08:00"
} as const;

export type ReleaseInfo = typeof RELEASE_INFO;
