import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const releaseConfigPath = path.join(rootDir, 'release.config.json');
const packageJsonPath = path.join(rootDir, 'package.json');
const buildGradlePath = path.join(rootDir, 'android', 'app', 'build.gradle');
const releaseInfoTsPath = path.join(rootDir, 'data', 'releaseInfo.ts');

const releaseConfig = JSON.parse(fs.readFileSync(releaseConfigPath, 'utf8'));

if (!Number.isInteger(releaseConfig.versionCode) || releaseConfig.versionCode <= 0) {
  throw new Error('release.config.json 中的 versionCode 必须是正整数。');
}

if (typeof releaseConfig.versionName !== 'string' || !releaseConfig.versionName.trim()) {
  throw new Error('release.config.json 中的 versionName 不能为空。');
}

const normalizedConfig = {
  ...releaseConfig,
  versionName: releaseConfig.versionName.trim(),
  releaseChannel: typeof releaseConfig.releaseChannel === 'string' && releaseConfig.releaseChannel.trim()
    ? releaseConfig.releaseChannel.trim()
    : 'stable'
};

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
if (packageJson.version !== normalizedConfig.versionName) {
  packageJson.version = normalizedConfig.versionName;
  fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`, 'utf8');
}

const buildGradle = fs.readFileSync(buildGradlePath, 'utf8')
  .replace(/versionCode\s+\d+/g, `versionCode ${normalizedConfig.versionCode}`)
  .replace(/versionName\s+"[^"]+"/g, `versionName "${normalizedConfig.versionName}"`);
fs.writeFileSync(buildGradlePath, buildGradle, 'utf8');

const releaseInfoSource = `// Auto-generated by scripts/sync-release.mjs. Do not edit manually.
export const RELEASE_INFO = ${JSON.stringify(normalizedConfig, null, 4)} as const;

export type ReleaseInfo = typeof RELEASE_INFO;
`;

fs.writeFileSync(releaseInfoTsPath, releaseInfoSource, 'utf8');

console.log(`Release synced: v${normalizedConfig.versionName} (${normalizedConfig.versionCode})`);
