import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const releaseConfigPath = path.join(rootDir, 'release.config.json');
const packageJsonPath = path.join(rootDir, 'package.json');
const buildGradlePath = path.join(rootDir, 'android', 'app', 'build.gradle');
const releaseInfoTsPath = path.join(rootDir, 'data', 'releaseInfo.ts');
const publicReleaseInfoPath = path.join(rootDir, 'public', 'release-info.json');

const releaseConfig = JSON.parse(fs.readFileSync(releaseConfigPath, 'utf8'));

if (!Number.isInteger(releaseConfig.versionCode) || releaseConfig.versionCode <= 0) {
  throw new Error('release.config.json 中的 versionCode 必须是正整数。');
}

if (typeof releaseConfig.versionName !== 'string' || !releaseConfig.versionName.trim()) {
  throw new Error('release.config.json 中的 versionName 不能为空。');
}

// 顶层 releasePublishedAt / changes / notes / releaseNotes 必须与 releaseHistory[0] 一致：
// changelog.html 的「最新版本」卡片直接读取顶层 releasePublishedAt 与 changes，
// 而 publish-apk-github-raw.mjs 等发布脚本也读取顶层 releasePublishedAt。
// 一旦升版本时只更新了 releaseHistory 却漏改顶层字段，线上更新日志就会
// 「版本号是新的、发布时间和内容还是上一版」。这里以 releaseHistory[0] 为准自动校正并回写配置。
const releaseHistory = Array.isArray(releaseConfig.releaseHistory) ? releaseConfig.releaseHistory : [];
const latestHistoryEntry = releaseHistory[0];
if (latestHistoryEntry && latestHistoryEntry.versionName === releaseConfig.versionName.trim()) {
  const latestNotes = Array.isArray(latestHistoryEntry.releaseNotes)
    ? latestHistoryEntry.releaseNotes.filter((item) => typeof item === 'string' && item.trim())
    : [];
  const latestPublishedAt = typeof latestHistoryEntry.releasePublishedAt === 'string'
    ? latestHistoryEntry.releasePublishedAt.trim()
    : '';
  const corrections = [];

  if (latestPublishedAt && releaseConfig.releasePublishedAt !== latestPublishedAt) {
    corrections.push(`releasePublishedAt: ${releaseConfig.releasePublishedAt || '(空)'} -> ${latestPublishedAt}`);
    releaseConfig.releasePublishedAt = latestPublishedAt;
  }

  if (latestNotes.length > 0) {
    if (!Array.isArray(releaseConfig.releaseNotes) || JSON.stringify(releaseConfig.releaseNotes) !== JSON.stringify(latestNotes)) {
      corrections.push(`releaseNotes: 已按 releaseHistory[0].releaseNotes 修正（${Array.isArray(releaseConfig.releaseNotes) ? releaseConfig.releaseNotes.length : 0} 条 -> ${latestNotes.length} 条）`);
      releaseConfig.releaseNotes = [...latestNotes];
    }
    if (!Array.isArray(releaseConfig.changes) || JSON.stringify(releaseConfig.changes) !== JSON.stringify(latestNotes)) {
      corrections.push(`changes: 已按 releaseHistory[0].releaseNotes 修正（${Array.isArray(releaseConfig.changes) ? releaseConfig.changes.length : 0} 条 -> ${latestNotes.length} 条）`);
      releaseConfig.changes = [...latestNotes];
    }
    const notesJoined = latestNotes.join('\n');
    if (releaseConfig.notes !== notesJoined) {
      corrections.push('notes: 已按 releaseHistory[0].releaseNotes 重新拼接');
      releaseConfig.notes = notesJoined;
    }
  }

  if (corrections.length > 0) {
    fs.writeFileSync(releaseConfigPath, `${JSON.stringify(releaseConfig, null, 2)}\n`, 'utf8');
    console.log('[sync-release] 已修正 release.config.json 顶层字段与 releaseHistory[0] 不一致的问题：');
    corrections.forEach((line) => console.log(`  - ${line}`));
  }
}

const normalizedConfig = {
  ...releaseConfig,
  versionName: releaseConfig.versionName.trim(),
  releaseChannel: typeof releaseConfig.releaseChannel === 'string' && releaseConfig.releaseChannel.trim()
    ? releaseConfig.releaseChannel.trim()
    : 'stable'
};

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
if (packageJson.version !== normalizedConfig.versionName) {
  packageJson.version = normalizedConfig.versionName;
  fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`, 'utf8');
}

const buildGradle = fs.readFileSync(buildGradlePath, 'utf8')
  .replace(/versionCode\s+\d+/g, `versionCode ${normalizedConfig.versionCode}`)
  .replace(/versionName\s+"[^"]+"/g, `versionName "${normalizedConfig.versionName}"`);
fs.writeFileSync(buildGradlePath, buildGradle, 'utf8');

const releaseInfoSource = `// Auto-generated by scripts/sync-release.mjs. Do not edit manually.
export const RELEASE_INFO = ${JSON.stringify(normalizedConfig, null, 4)} as const;

export type ReleaseInfo = typeof RELEASE_INFO;
`;

fs.writeFileSync(releaseInfoTsPath, releaseInfoSource, 'utf8');
fs.writeFileSync(publicReleaseInfoPath, `${JSON.stringify(normalizedConfig, null, 2)}\n`, 'utf8');

console.log(`Release synced: v${normalizedConfig.versionName} (${normalizedConfig.versionCode})`);
